steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['./deploy.sh']
  
  dir: 'website'
  #  args: ['-c', 'gcloud functions deploy merchantmap --set-env-vars=API_KEY=$$API_KEY  --entry-point=app --region=us-central1 --source=website --trigger-http --allow-unauthenticated  --runtime=nodejs14']
  secretEnv: ['API_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/918652732143/secrets/AIRTABLE_API/versions/latest
    env: 'API_KEY'
